### ISSUE TITLE
ERROR_DOWNLOAD_IMAGE_FAILED

### ISSUE THREAD

**Issue by zhuifeng1017** [tencentyun/wafer2-ci-nodejs-demo#1]
调用ci.ocr接口返回错误，
{"code":0,"data":{"code":-1308,"message":"ERROR_DOWNLOAD_IMAGE_FAILED","data":{"class":[],"items":[]}}}

**Comment by jas0ncn** [comment]
可以设置一下你的cos的bucket为共有读私有写
