### ISSUE TITLE
'nodemon' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by zxs1215** [tencentyun/wafer2-ci-nodejs-demo#2]
` npm run dev

> koa-weapp-demo@1.0.0 dev E:\wexinmini\wafer2-ci-nodejs-demo\server
> nodemon --config nodemon.json app.js

'nodemon' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koa-weapp-demo@1.0.0 dev: `nodemon --config nodemon.json app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-weapp-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-08-11T07_32_13_881Z-debug.log`

**Comment by jas0ncn** [comment]
全局安装一下 nodemon 哈

**Comment by CYLCN** [comment]
就是全局装了还还是报这个错
